#pragma once

#define LAYER_STATE_16BIT

#define NO_MUSIC_MODE
#define NO_ACTION_ONESHOT
#define NO_ACTION_TAPPING

#define MACRO_TIMER 5

#define MK_COMBINED
#define MOUSEKEY_DELAY 100
#define MOUSEKEY_INTERVAL 16
#define MOUSEKEY_MOVE_DELTA 20
#define MOUSEKEY_MAX_SPEED 5
#define MOUSEKEY_TIME_TO_MAX 100
#define MOUSEKEY_WHEEL_DELAY 100
#define MOUSEKEY_WHEEL_INTERVAL 50
#define MOUSEKEY_WHEEL_MAX_SPEED 8
#define MOUSEKEY_WHEEL_TIME_TO_MAX 100

#define KEYBOARD_AURORA_SWEEP

// When using a RP2040 controller this will identify the master correctly
#ifdef CONVERT_TO_PROMICRO_RP2040
#    define USB_VBUS_PIN 19U
#endif
