#pragma once

enum ekeycode_ranges
{
    CUSHI_KEYCODES_START = SAFE_RANGE,
    CUSHI_KEYCODES_END = CUSHI_KEYCODES_START + 32,
    CUKEY_KEYCODES_START = CUSHI_KEYCODES_END,
    CUKEY_KEYCODES_END = CUKEY_KEYCODES_START + 16,
    ONESHOT_KEYCODES_START = CUKEY_KEYCODES_END,
    ONESHOT_KEYCODES_END = ONESHOT_KEYCODES_START + 4,
    SECRET_KEYCODES_START = ONESHOT_KEYCODES_END,
    SECRET_KEYCODES_END = SECRET_KEYCODES_START + 16,
    FEATURE_KEYCODES_START = SECRET_KEYCODES_END,
    FEATURE_KEYCODES_END = FEATURE_KEYCODES_START + 8,
    USER_KEYCODES_START = FEATURE_KEYCODES_END,
    USER_KEYCODES_END = USER_KEYCODES_START + 32,
};