#pragma once
#undef MATRIX_ROW_PINS
#undef MATRIX_ROW_PINS_RIGHT
#undef MATRIX_COL_PINS
#undef MATRIX_COL_PINS_RIGHT
#undef ENCODERS_PAD_A
#undef ENCODERS_PAD_B
#undef ENCODERS_PAD_A_RIGHT
#undef ENCODERS_PAD_B_RIGHT 
#undef SOFT_SERIAL_PIN
#undef RGB_DI_PIN
#undef SPLIT_HAND_MATRIX_GRID
#define MATRIX_ROW_PINS {GP27, GP26, GP22, GP20}
#define MATRIX_ROW_PINS_RIGHT {GP4, GP5, GP6, GP7}
#define MATRIX_COL_PINS {GP23, GP21, GP9, GP8, GP7, GP6, GP5, GP4}
#define MATRIX_COL_PINS_RIGHT {GP8, GP9, GP21, GP23, GP20, GP22, GP26, GP27}
#define ENCODERS_PAD_A {GP29}
#define ENCODERS_PAD_B {GP28}
#define ENCODERS_PAD_A_RIGHT {GP28}
#define ENCODERS_PAD_B_RIGHT {GP29}
#define SERIAL_USART_TX_PIN GP1
#define RGB_DI_PIN GP0
#define SPLIT_HAND_MATRIX_GRID GP7, GP20
#define I2C_DRIVER I2CD1
#define I2C1_SDA_PIN GP16
#define I2C1_SCL_PIN GP17
#define SPLIT_POINTING_ENABLE
#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET
#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET_TIMEOUT 200U
#define POINTING_DEVICE_RIGHT
#ifdef RGBLIGHT_ENABLE
#define RGBLIGHT_ANIMATIONS
#define RGBLIGHT_SLEEP
#define RGBLIGHT_HUE_STEP 5
#define RGBLIGHT_SAT_STEP 5
#endif
